### ISSUE TITLE
issues/suggestions 

### ISSUE THREAD

**Issue by Andyauk** [polisek/qbr-inventory-by-polisek#1]
if you have say a shotgun on number 1. on press it uses it, to put in hand 
and tab to puts on your back, but if you press 1 again it removes it from your back and in tab menu.

unable to use a bow, as it has 0 ammo so you cant put in your hand like you can a gun when its empty, 
so maybe have a bow spawn in with 1 ammo.

**Comment by polisek** [comment]
Bow ammo fixed.

When you draw your bow it will check if you have arrows.
If you do it will automatically reload when the bow is empty.

**Comment by polisek** [comment]
> if you have say a shotgun on number 1. on press it uses it, to put in hand and tab to puts on your back, but if you press 1 again it removes it from your back and in tab menu.
> 
> unable to use a bow, as it has 0 ammo so you cant put in your hand like you can a gun when its empty, so maybe have a bow spawn in with 1 ammo.

**Comment by polisek** [comment]
> if you have say a shotgun on number 1. on press it uses it, to put in hand and tab to puts on your back, but if you press 1 again it removes it from your back and in tab menu.
> 
> unable to use a bow, as it has 0 ammo so you cant put in your hand like you can a gun when its empty, so maybe have a bow spawn in with 1 ammo.

Bow ammo fixed.

When you draw your bow it will check if you have arrows.
If you do it will automatically reload when the bow is empty.
