### ISSUE TITLE
not deleting after use

### ISSUE THREAD

**Issue by Andyauk** [polisek/qbr-inventory-by-polisek#2]
these are not deleting after use.

weapon_thrown_throwing_knives
weapon_thrown_tomahawk
weapon_thrown_tomahawk_ancient
weapon_thrown_bolas

**Comment by Andyauk** [comment]
i guess due to them being able to be picked back up.

**Comment by polisek** [comment]
> i guess due to them being able to be picked back up.

Yes, I didn't delete throwable items for the reason that they can be collected back.
And if you pick something off the ground.
It'll saved the number of things you have.

Molotov and dynamite cannot be taken back.

Its not bug its feature :D
